### ISSUE TITLE
How to test the engine without Evaluator?

### ISSUE THREAD

**Issue by shuvoxcd01** [Mohanned29/Chess-Engine-Jinxy#1]
Getting the following error:
`ModuleNotFoundError: No module named 'src.engine.Evaluator'
`

Upon investigation I found the following in the .gitignore:
```
#Evaluation function file
2ndVersion/src/engine/Evaluator.py
#the tesing file
2ndVersion/test.py

# the evaluation function has been hidden , its still under development
```

I want to test out the engine with the provided checkpoint - but I don't know how to do that as the Evaluator has not been provided.

**Comment by Mohanned29** [comment]
Hiii , hope you are doing well , in the readme its mentionned that this repo is only to veiw the code purposes , the evaluation function is not finished yet to be posted

**Comment by Mezghenna-Mohanned** [comment]
> Getting the following error:
> `ModuleNotFoundError: No module named 'src.engine.Evaluator'
> `
> 
> Upon investigation I found the following in the .gitignore:
> ```
> #Evaluation function file
> 2ndVersion/src/engine/Evaluator.py
> #the tesing file
> 2ndVersion/test.py
> 
> # the evaluation function has been hidden , its still under development
> ```
> 
> I want to test out the engine with the provided checkpoint - but I don't know how to do that as the Evaluator has not been provided.
> 



Hiii , hope you are doing well , in the readme its mentionned that this repo is only for veiw the code purposes , the evaluation function is not finished yet to be posted

**Comment by shuvoxcd01** [comment]
Thanks!
